// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAau03JkXESSfzjS83LcyQeKi6v94QLDKI',
    appId: '1:526271683994:web:88c88be9eb3efc542f6e23',
    messagingSenderId: '526271683994',
    projectId: 'crudd-725f3',
    authDomain: 'crudd-725f3.firebaseapp.com',
    storageBucket: 'crudd-725f3.firebasestorage.app',
    measurementId: 'G-QX2N9ER0NT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA39ZS7JlNRRrz8qWh7U8-mLVQv7UPNL94',
    appId: '1:526271683994:android:9e1c0d136003c7ba2f6e23',
    messagingSenderId: '526271683994',
    projectId: 'crudd-725f3',
    storageBucket: 'crudd-725f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAL3SlrIZseLIh-G7-QtPzkYkVayXDGVA',
    appId: '1:526271683994:ios:4bc1b9953909dbfe2f6e23',
    messagingSenderId: '526271683994',
    projectId: 'crudd-725f3',
    storageBucket: 'crudd-725f3.firebasestorage.app',
    iosBundleId: 'com.example.holydays',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAL3SlrIZseLIh-G7-QtPzkYkVayXDGVA',
    appId: '1:526271683994:ios:4bc1b9953909dbfe2f6e23',
    messagingSenderId: '526271683994',
    projectId: 'crudd-725f3',
    storageBucket: 'crudd-725f3.firebasestorage.app',
    iosBundleId: 'com.example.holydays',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAau03JkXESSfzjS83LcyQeKi6v94QLDKI',
    appId: '1:526271683994:web:06aaa27724871d752f6e23',
    messagingSenderId: '526271683994',
    projectId: 'crudd-725f3',
    authDomain: 'crudd-725f3.firebaseapp.com',
    storageBucket: 'crudd-725f3.firebasestorage.app',
    measurementId: 'G-EDZYYV591Y',
  );
}
